In [1]:
import tensorflow as tf
import numpy as np

In [2]:
X = np.array([[0.0, 0.0],
              [0.0, 1.0],
              [1.0, 0.0],
              [1.0, 1.0]])
X

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]])

In [3]:
y = np.array([[0.0], [1.0], [1.0], [1.0]])
y

array([[0.],
       [1.],
       [1.],
       [1.]])

In [4]:
W = tf.Variable(tf.zeros([2, 1], dtype = tf.float64))
type(W)

tensorflow.python.ops.variables.RefVariable

In [5]:
def step(x):
    return tf.cast(tf.to_float(tf.math.greater_equal(x, 1)), tf.float64)

In [6]:
print(W)

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float64_ref>


In [7]:
init = tf.global_variables_initializer()

In [8]:
camada_saida = tf.matmul(X, W)

In [9]:
camada_saida_ativacao = step(camada_saida)

In [10]:
erro = tf.subtract(y, camada_saida_ativacao)

In [11]:
delta = tf.matmul(X, erro, transpose_a = True)
treinamento = tf.assign(W, tf.add(W, tf.multiply(delta, 0.1)))

In [12]:
with tf.Session() as sess:
    sess.run(init)
    #print(sess.run(W))
    #print(sess.run(camada_saida))
    
    #print(sess.run(tf.to_float(tf.math.greater_equal(1, 1))))
    #print(sess.run(step(1)))
    #print('\n')
    #print(sess.run(camada_saida_ativacao))
    print('\n')
    #print(sess.run(erro))
    #print(X)
    #print('\n')
    #print(sess.run(tf.transpose(X)))
    #print(sess.run(treinamento))
    epoca = 0
    for i in range(15):
        epoca += 1
        erro_total, _ = sess.run([erro, treinamento])
        erro_soma = tf.reduce_sum(erro_total)
        #print(erro_total)
        print('Época:', epoca, ' Erro: ', sess.run(erro_soma))
        if erro_soma.eval() == 0.0:
            break
    W_final = sess.run(W)




Época: 1  Erro:  3.0
Época: 2  Erro:  3.0
Época: 3  Erro:  3.0
Época: 4  Erro:  2.0
Época: 5  Erro:  2.0
Época: 6  Erro:  2.0
Época: 7  Erro:  2.0
Época: 8  Erro:  0.0


In [13]:
W_final

array([[1.],
       [1.]])

In [14]:
# teste
camada_saida_teste = tf.matmul(X, W_final)
camada_saida_ativacao_teste = step(camada_saida_teste)
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(camada_saida_ativacao_teste))

[[0.]
 [1.]
 [1.]
 [1.]]
