In [1]:
import tensorflow as tf

In [2]:
a = tf.constant([[1,2], [3,4]])
b = tf.constant([[-1, 3], [4, 2]])

In [3]:
multiplicacao = tf.matmul(a, b)

In [4]:
with tf.Session() as sess:
    print(sess.run(a))
    print('\n')
    print(sess.run(b))
    print('\n')
    print(sess.run(multiplicacao))

[[1 2]
 [3 4]]


[[-1  3]
 [ 4  2]]


[[ 7  7]
 [13 17]]


In [5]:
multiplicacao2 = tf.matmul(b, a)

In [6]:
with tf.Session() as sess:
    print(sess.run(multiplicacao2))

[[ 8 10]
 [10 16]]


In [7]:
a1 = tf.constant([[2,3],[0,1], [-1,4]])
b1 = tf.constant([[1,2,3], [-2,0,4]])
multiplicacao3 = tf.matmul(a1, b1)

In [8]:
with tf.Session() as sess:
    print(sess.run(a1))
    print('\n')
    print(sess.run(b1))
    print('\n')
    print(sess.run(multiplicacao3))

[[ 2  3]
 [ 0  1]
 [-1  4]]


[[ 1  2  3]
 [-2  0  4]]


[[-4  4 18]
 [-2  0  4]
 [-9 -2 13]]
