In [1]:
import pandas as pd
base = pd.read_csv('house_prices.csv')
base.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view     ...      grade  sqft_above  \
0      5650     1.0           0     0     ...          7        1180   
1      7242     2.0           0     0     ...          7        2170   
2     10000     1.0           0     0     ...          6         770   
3      5000     1.0           0     0     ...          7        1050   
4      8080     1.0           0     0     ...          8        1680   

   sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
0              0      1955             0    98178  47.5112 -122.257   
1            400      1951          1991    98125  47.7210 -122.319   
2              0      1933             0    98028  47.7379 -122.233   
3            910      1965             0    98136  47.5208 -122.393   
4              0      1987             0    98074  47.6168 -122.045   

   sqft_living15  sqft_lot15  
0           1340        5650  
1           1690        7639  
2           2720        8062  
3           1360        5000  
4           1800        7503  

[5 rows x 21 columns]

In [2]:
base.columns

Index(['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long', 'sqft_living15', 'sqft_lot15'],
      dtype='object')

In [3]:
colunas_usadas = ['price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long']

In [4]:
colunas_usadas

['price',
 'bedrooms',
 'bathrooms',
 'sqft_living',
 'sqft_lot',
 'floors',
 'waterfront',
 'view',
 'condition',
 'grade',
 'sqft_above',
 'sqft_basement',
 'yr_built',
 'yr_renovated',
 'zipcode',
 'lat',
 'long']

In [5]:
base = pd.read_csv('house_prices.csv', usecols = colunas_usadas)

In [6]:
base.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  221900.0         3       1.00         1180      5650     1.0           0   
1  538000.0         3       2.25         2570      7242     2.0           0   
2  180000.0         2       1.00          770     10000     1.0           0   
3  604000.0         4       3.00         1960      5000     1.0           0   
4  510000.0         3       2.00         1680      8080     1.0           0   

   view  condition  grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0     0          3      7        1180              0      1955             0   
1     0          3      7        2170            400      1951          1991   
2     0          3      6         770              0      1933             0   
3     0          5      7        1050            910      1965             0   
4     0          3      8        1680              0      1987             0   

   zipcode      lat     long  
0    98178  47.5112 -122.257  
1    98125  47.7210 -122.319  
2    98028  47.7379 -122.233  
3    98136  47.5208 -122.393  
4    98074  47.6168 -122.045

In [7]:
from sklearn.preprocessing import MinMaxScaler
scaler_x = MinMaxScaler()
base[['bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long']] = scaler_x.fit_transform(base[['bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long']])

/home/luizbag/anaconda3/envs/tensorflow/lib/python3.6/site-packages/sklearn/preprocessing/data.py:323: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)


In [8]:
base.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  221900.0  0.090909    0.12500     0.067170  0.003108     0.0         0.0   
1  538000.0  0.090909    0.28125     0.172075  0.004072     0.4         0.0   
2  180000.0  0.060606    0.12500     0.036226  0.005743     0.0         0.0   
3  604000.0  0.121212    0.37500     0.126038  0.002714     0.0         0.0   
4  510000.0  0.090909    0.25000     0.104906  0.004579     0.0         0.0   

   view  condition     grade  sqft_above  sqft_basement  yr_built  \
0   0.0        0.5  0.500000    0.097588       0.000000  0.478261   
1   0.0        0.5  0.500000    0.206140       0.082988  0.443478   
2   0.0        0.5  0.416667    0.052632       0.000000  0.286957   
3   0.0        1.0  0.500000    0.083333       0.188797  0.565217   
4   0.0        0.5  0.583333    0.152412       0.000000  0.756522   

   yr_renovated   zipcode       lat      long  
0      0.000000  0.893939  0.571498  0.217608  
1      0.988089  0.626263  0.908959  0.166113  
2      0.000000  0.136364  0.936143  0.237542  
3      0.000000  0.681818  0.586939  0.104651  
4      0.000000  0.368687  0.741354  0.393688

In [9]:
scaler_y = MinMaxScaler()
base[['price']] = scaler_y.fit_transform(base[['price']])

In [10]:
base.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  0.019266  0.090909    0.12500     0.067170  0.003108     0.0         0.0   
1  0.060721  0.090909    0.28125     0.172075  0.004072     0.4         0.0   
2  0.013770  0.060606    0.12500     0.036226  0.005743     0.0         0.0   
3  0.069377  0.121212    0.37500     0.126038  0.002714     0.0         0.0   
4  0.057049  0.090909    0.25000     0.104906  0.004579     0.0         0.0   

   view  condition     grade  sqft_above  sqft_basement  yr_built  \
0   0.0        0.5  0.500000    0.097588       0.000000  0.478261   
1   0.0        0.5  0.500000    0.206140       0.082988  0.443478   
2   0.0        0.5  0.416667    0.052632       0.000000  0.286957   
3   0.0        1.0  0.500000    0.083333       0.188797  0.565217   
4   0.0        0.5  0.583333    0.152412       0.000000  0.756522   

   yr_renovated   zipcode       lat      long  
0      0.000000  0.893939  0.571498  0.217608  
1      0.988089  0.626263  0.908959  0.166113  
2      0.000000  0.136364  0.936143  0.237542  
3      0.000000  0.681818  0.586939  0.104651  
4      0.000000  0.368687  0.741354  0.393688

In [11]:
X = base.drop('price', axis = 1)
y = base.price

In [12]:
X.head()

bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view  \
0  0.090909    0.12500     0.067170  0.003108     0.0         0.0   0.0   
1  0.090909    0.28125     0.172075  0.004072     0.4         0.0   0.0   
2  0.060606    0.12500     0.036226  0.005743     0.0         0.0   0.0   
3  0.121212    0.37500     0.126038  0.002714     0.0         0.0   0.0   
4  0.090909    0.25000     0.104906  0.004579     0.0         0.0   0.0   

   condition     grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0        0.5  0.500000    0.097588       0.000000  0.478261      0.000000   
1        0.5  0.500000    0.206140       0.082988  0.443478      0.988089   
2        0.5  0.416667    0.052632       0.000000  0.286957      0.000000   
3        1.0  0.500000    0.083333       0.188797  0.565217      0.000000   
4        0.5  0.583333    0.152412       0.000000  0.756522      0.000000   

    zipcode       lat      long  
0  0.893939  0.571498  0.217608  
1  0.626263  0.908959  0.166113  
2  0.136364  0.936143  0.237542  
3  0.681818  0.586939  0.104651  
4  0.368687  0.741354  0.393688

In [ ]:
type(X)

In [13]:
y.head()

0    0.019266
1    0.060721
2    0.013770
3    0.069377
4    0.057049
Name: price, dtype: float64

In [ ]:
type(y)

In [14]:
previsores_colunas = colunas_usadas[1:17]
previsores_colunas

['bedrooms',
 'bathrooms',
 'sqft_living',
 'sqft_lot',
 'floors',
 'waterfront',
 'view',
 'condition',
 'grade',
 'sqft_above',
 'sqft_basement',
 'yr_built',
 'yr_renovated',
 'zipcode',
 'lat',
 'long']

In [15]:
import tensorflow as tf

In [16]:
colunas = [tf.feature_column.numeric_column(key = c) for c in previsores_colunas]

In [18]:
print(colunas[0])

_NumericColumn(key='bedrooms', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)


In [19]:
from sklearn.model_selection import train_test_split
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X, y, test_size = 0.3)

In [20]:
X_treinamento.shape

(15129, 16)

In [21]:
y_treinamento.shape

(15129,)

In [22]:
X_teste.shape

(6484, 16)

In [23]:
funcao_treinamento = tf.estimator.inputs.pandas_input_fn(x = X_treinamento, y = y_treinamento,
                                                        batch_size = 32, num_epochs = None, shuffle = True)

In [24]:
funcao_teste = tf.estimator.inputs.pandas_input_fn(x = X_teste, y = y_teste,
                                                   batch_size = 32, num_epochs = 10000, shuffle = False)

In [25]:
regressor = tf.estimator.LinearRegressor(feature_columns=colunas)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/tmp/tmpalafeb4m', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f62d3fd5978>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [26]:
regressor.train(input_fn=funcao_treinamento, steps = 10000)

Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Saving checkpoints for 0 into /tmp/tmpalafeb4m/model.ckpt.
INFO:tensorflow:loss = 0.20681503, step = 1
INFO:tensorflow:global_step/sec: 297.743
INFO:tensorflow:loss = 0.00864659, step = 101 (0.338 sec)
INFO:tensorflow:global_step/sec: 424.693
INFO:tensorflow:loss = 0.011250844, step = 201 (0.237 sec)
INFO:tensorflow:global_step/sec: 419.836
INFO:tensorflow:loss = 0.034152277, step = 301 (0.237 sec)
INFO:tensorflow:global_step/sec: 417.533
INFO:tensorflow:loss = 0.04033105, step = 401 (0.239 se

INFO:tensorflow:global_step/sec: 382.752
INFO:tensorflow:loss = 0.012742457, step = 6801 (0.262 sec)
INFO:tensorflow:global_step/sec: 382.804
INFO:tensorflow:loss = 0.009106565, step = 6901 (0.260 sec)
INFO:tensorflow:global_step/sec: 384.321
INFO:tensorflow:loss = 0.04991552, step = 7001 (0.261 sec)
INFO:tensorflow:global_step/sec: 383.59
INFO:tensorflow:loss = 0.01944165, step = 7101 (0.261 sec)
INFO:tensorflow:global_step/sec: 416.416
INFO:tensorflow:loss = 0.012925988, step = 7201 (0.240 sec)
INFO:tensorflow:global_step/sec: 426.775
INFO:tensorflow:loss = 0.020916928, step = 7301 (0.233 sec)
INFO:tensorflow:global_step/sec: 423.208
INFO:tensorflow:loss = 0.008019909, step = 7401 (0.237 sec)
INFO:tensorflow:global_step/sec: 430.292
INFO:tensorflow:loss = 0.02202911, step = 7501 (0.232 sec)
INFO:tensorflow:global_step/sec: 400.333
INFO:tensorflow:loss = 0.0066951956, step = 7601 (0.250 sec)
INFO:tensorflow:global_step/sec: 421.4
INFO:tensorflow:loss = 0.016026624, step = 7701 (0.236 

In [27]:
metricas_treinamento = regressor.evaluate(input_fn=funcao_treinamento, steps = 10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2019-01-23-23:13:21
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpalafeb4m/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Evaluation [5000/10000]
INFO:tensorflow:Evaluation [6000/10000]
INFO:tensorflow:Evaluation [7000/10000]
INFO:tensorflow:Evaluation [8000/10000]
INFO:tensorflow:Evaluation [9000/10000]
INFO:tensorflow:Evaluation [10000/10000]
INFO:tensorflow:Finished evaluation at 2019-01-23-23:13:43
INFO:tensorflow:Saving dict for global step 10000: average_loss = 0.0006924802, global_step = 10000, label/mean = 0.06062378, loss = 0.022159366, prediction/mean = 0.054673914
INFO:tensorflow:Saving 'checkpoint_p

In [28]:
metricas_teste = regressor.evaluate(input_fn=funcao_teste, steps = 10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2019-01-23-23:13:48
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpalafeb4m/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Evaluation [5000/10000]
INFO:tensorflow:Evaluation [6000/10000]
INFO:tensorflow:Evaluation [7000/10000]
INFO:tensorflow:Evaluation [8000/10000]
INFO:tensorflow:Evaluation [9000/10000]
INFO:tensorflow:Evaluation [10000/10000]
INFO:tensorflow:Finished evaluation at 2019-01-23-23:14:09
INFO:tensorflow:Saving dict for global step 10000: average_loss = 0.0008681346, global_step = 10000, label/mean = 0.061862096, loss = 0.027780307, prediction/mean = 0.055518664
INFO:tensorflow:Saving 'checkpoint_

In [29]:
metricas_treinamento

{'average_loss': 0.0006924802,
 'label/mean': 0.06062378,
 'loss': 0.022159366,
 'prediction/mean': 0.054673914,
 'global_step': 10000}

In [30]:
metricas_teste

{'average_loss': 0.0008681346,
 'label/mean': 0.061862096,
 'loss': 0.027780307,
 'prediction/mean': 0.055518664,
 'global_step': 10000}

In [31]:
funcao_previsao = tf.estimator.inputs.pandas_input_fn(x = X_teste, shuffle = False)

In [32]:
previsoes = regressor.predict(input_fn=funcao_previsao)

In [33]:
list(previsoes)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpalafeb4m/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


[{'predictions': array([0.09854305], dtype=float32)},
 {'predictions': array([-0.002264], dtype=float32)},
 {'predictions': array([0.03425131], dtype=float32)},
 {'predictions': array([0.02191614], dtype=float32)},
 {'predictions': array([0.0031587], dtype=float32)},
 {'predictions': array([0.02004632], dtype=float32)},
 {'predictions': array([0.05822192], dtype=float32)},
 {'predictions': array([0.02009395], dtype=float32)},
 {'predictions': array([0.05181687], dtype=float32)},
 {'predictions': array([0.02084081], dtype=float32)},
 {'predictions': array([0.0838778], dtype=float32)},
 {'predictions': array([0.06152995], dtype=float32)},
 {'predictions': array([0.0264185], dtype=float32)},
 {'predictions': array([0.05116183], dtype=float32)},
 {'predictions': array([0.05161536], dtype=float32)},
 {'predictions': array([0.16557127], dtype=float32)},
 {'predictions': array([0.03270907], dtype=float32)},
 {'predictions': array([0.13504532], dtype=float32)},
 {'predictions': array([0.043042

In [34]:
valores_previsoes = []
for p in regressor.predict(input_fn=funcao_previsao):
    valores_previsoes.append(p['predictions'])

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpalafeb4m/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


In [35]:
valores_previsoes

[array([0.09854305], dtype=float32),
 array([-0.002264], dtype=float32),
 array([0.03425131], dtype=float32),
 array([0.02191614], dtype=float32),
 array([0.0031587], dtype=float32),
 array([0.02004632], dtype=float32),
 array([0.05822192], dtype=float32),
 array([0.02009395], dtype=float32),
 array([0.05181687], dtype=float32),
 array([0.02084081], dtype=float32),
 array([0.0838778], dtype=float32),
 array([0.06152995], dtype=float32),
 array([0.0264185], dtype=float32),
 array([0.05116183], dtype=float32),
 array([0.05161536], dtype=float32),
 array([0.16557127], dtype=float32),
 array([0.03270907], dtype=float32),
 array([0.13504532], dtype=float32),
 array([0.04304299], dtype=float32),
 array([0.02478784], dtype=float32),
 array([0.03378057], dtype=float32),
 array([0.05057105], dtype=float32),
 array([0.00378104], dtype=float32),
 array([0.09590554], dtype=float32),
 array([0.01148644], dtype=float32),
 array([0.02672933], dtype=float32),
 array([0.00671596], dtype=float32),
 arra

In [36]:
import numpy as np
valores_previsoes = np.asarray(valores_previsoes).reshape(-1,1)

In [37]:
valores_previsoes

array([[ 0.09854305],
       [-0.002264  ],
       [ 0.03425131],
       ...,
       [ 0.03978639],
       [ 0.0688031 ],
       [ 0.07980332]], dtype=float32)

In [38]:
valores_previsoes = scaler_y.inverse_transform(valores_previsoes)
valores_previsoes

array([[826390.75 ],
       [ 57736.996],
       [336166.25 ],
       ...,
       [378371.25 ],
       [599623.6  ],
       [683500.25 ]], dtype=float32)

In [39]:
y_teste

1341     0.116066
15458    0.017443
11919    0.051384
10356    0.055738
9037     0.022951
18629    0.040000
5461     0.052459
15671    0.035410
4817     0.043934
12110    0.019279
10388    0.074820
6368     0.048630
12630    0.020328
11203    0.051934
18062    0.050098
19357    0.173770
11236    0.068197
12721    0.078033
20554    0.044759
8982     0.019672
14724    0.036066
12065    0.076852
2493     0.015738
4727     0.075410
12049    0.025574
569      0.043279
3331     0.040000
17395    0.033574
1657     0.042623
14312    0.074754
           ...   
17414    0.087082
9525     0.027007
8310     0.019672
20647    0.060977
3151     0.041180
12656    0.078820
12145    0.020459
3837     0.041967
1378     0.026780
19802    0.061639
11226    0.173770
21445    0.059824
13492    0.206557
8572     0.027803
10097    0.062951
6758     0.028852
7377     0.087213
3266     0.045902
2063     0.057049
8811     0.088525
15561    0.057049
10169    0.015541
17378    0.013757
1016     0.058361
6690     0

In [40]:
y_teste.shape

(6484,)

In [41]:
y_teste2 = y_teste.values.reshape(-1,1)
y_teste2.shape

(6484, 1)

In [42]:
y_teste2 = scaler_y.inverse_transform(y_teste2)

In [43]:
y_teste2

array([[960000.],
       [208000.],
       [466800.],
       ...,
       [450000.],
       [599990.],
       [700000.]])

In [44]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_teste2, valores_previsoes)

In [45]:
mae

134439.82962350533