In [1]:
import pandas as pd
base = pd.read_csv('house_prices.csv')
base.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view     ...      grade  sqft_above  \
0      5650     1.0           0     0     ...          7        1180   
1      7242     2.0           0     0     ...          7        2170   
2     10000     1.0           0     0     ...          6         770   
3      5000     1.0           0     0     ...          7        1050   
4      8080     1.0           0     0     ...          8        1680   

   sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
0              0      1955             0    98178  47.5112 -122.257   
1            400      1951          1991    98125  47.7210 -122.319   
2              0      1933             0    98028  47.7379 -122.233   
3            910      1965             0    98136  47.5208 -122.393   
4              0      1987             0    98074  47.6168 -122.045   

   sqft_living15  sqft_lot15  
0           1340        5650  
1           1690        7639  
2           2720        8062  
3           1360        5000  
4           1800        7503  

[5 rows x 21 columns]

In [2]:
base.shape

(21613, 21)

In [4]:
X = base.iloc[:, 5:6].values
y = base.iloc[:, 2:3].values

In [5]:
X

array([[1180],
       [2570],
       [ 770],
       ...,
       [1020],
       [1600],
       [1020]])

In [6]:
y

array([[221900.],
       [538000.],
       [180000.],
       ...,
       [402101.],
       [400000.],
       [325000.]])

In [7]:
from sklearn.preprocessing import StandardScaler
scaler_x = StandardScaler()
X = scaler_x.fit_transform(X)
scaler_y = StandardScaler()
y = scaler_y.fit_transform(y)

/home/luizbag/anaconda3/envs/tensorflow/lib/python3.6/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/home/luizbag/anaconda3/envs/tensorflow/lib/python3.6/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [8]:
X

array([[-0.97983502],
       [ 0.53363434],
       [-1.42625404],
       ...,
       [-1.15404732],
       [-0.52252773],
       [-1.15404732]])

In [9]:
y

array([[-0.86671733],
       [-0.00568792],
       [-0.98084935],
       ...,
       [-0.37586519],
       [-0.38158814],
       [-0.58588173]])

In [10]:
import tensorflow as tf

In [11]:
colunas = [tf.feature_column.numeric_column('x', shape = [1])]

In [12]:
colunas

[_NumericColumn(key='x', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)]

In [13]:
regressor = tf.estimator.LinearRegressor(feature_columns=colunas)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/tmp/tmpqw2efpds', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f7d43b83198>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [14]:
from sklearn.model_selection import train_test_split
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X, y, test_size = 0.3)

In [15]:
X_treinamento.shape

(15129, 1)

In [16]:
y_treinamento.shape

(15129, 1)

In [17]:
X_teste.shape

(6484, 1)

In [18]:
y_teste.shape

(6484, 1)

In [19]:
funcao_treinamento = tf.estimator.inputs.numpy_input_fn({'x': X_treinamento}, y_treinamento,
                                                        batch_size = 32, num_epochs = None, 
                                                        shuffle = True)

In [20]:
funcao_teste = tf.estimator.inputs.numpy_input_fn({'x': X_teste}, y_teste, batch_size = 32, 
                                                  num_epochs = 1000, shuffle = False)

In [21]:
regressor.train(input_fn = funcao_treinamento, steps = 10000)

Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Saving checkpoints for 0 into /tmp/tmpqw2efpds/model.ckpt.
INFO:tensorflow:loss = 27.401388, step = 1
INFO:tensorflow:global_step/sec: 866.869
INFO:tensorflow:loss = 16.772003, step = 101 (0.116 sec)
INFO:tensorflow:global_step/sec: 1190.87
INFO:tensorflow:loss = 7.797895, step = 201 (0.084 sec)
INFO:tensorflow:global_step/sec: 1109.77
INFO:tensorflow:loss = 25.195791, step = 301 (0.090 sec)
INFO:tensorflow:global_step/sec: 1274.54
INFO:tensorflow:loss = 7.9770994, step = 401 (0.079 sec)
INFO:

INFO:tensorflow:global_step/sec: 1003.59
INFO:tensorflow:loss = 10.582952, step = 7001 (0.100 sec)
INFO:tensorflow:global_step/sec: 1009.98
INFO:tensorflow:loss = 11.428911, step = 7101 (0.099 sec)
INFO:tensorflow:global_step/sec: 1015.75
INFO:tensorflow:loss = 16.686607, step = 7201 (0.099 sec)
INFO:tensorflow:global_step/sec: 1074.86
INFO:tensorflow:loss = 17.62306, step = 7301 (0.092 sec)
INFO:tensorflow:global_step/sec: 1112.66
INFO:tensorflow:loss = 49.556778, step = 7401 (0.090 sec)
INFO:tensorflow:global_step/sec: 1098.84
INFO:tensorflow:loss = 8.833002, step = 7501 (0.091 sec)
INFO:tensorflow:global_step/sec: 1107.77
INFO:tensorflow:loss = 11.222549, step = 7601 (0.090 sec)
INFO:tensorflow:global_step/sec: 1100.97
INFO:tensorflow:loss = 18.85415, step = 7701 (0.091 sec)
INFO:tensorflow:global_step/sec: 1266.33
INFO:tensorflow:loss = 8.482089, step = 7801 (0.078 sec)
INFO:tensorflow:global_step/sec: 1108.49
INFO:tensorflow:loss = 39.906975, step = 7901 (0.090 sec)
INFO:tensorflo

In [22]:
metricas_treinamento = regressor.evaluate(input_fn = funcao_treinamento, steps = 10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2019-01-23-22:04:55
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpqw2efpds/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Evaluation [5000/10000]
INFO:tensorflow:Evaluation [6000/10000]
INFO:tensorflow:Evaluation [7000/10000]
INFO:tensorflow:Evaluation [8000/10000]
INFO:tensorflow:Evaluation [9000/10000]
INFO:tensorflow:Evaluation [10000/10000]
INFO:tensorflow:Finished evaluation at 2019-01-23-22:05:02
INFO:tensorflow:Saving dict for global step 10000: average_loss = 0.5055223, global_step = 10000, label/mean = -0.0077094375, loss = 16.176714, prediction/mean = -0.018214094
INFO:tensorflow:Saving 'checkpoint_pa

In [23]:
metricas_teste = regressor.evaluate(input_fn = funcao_teste, steps = 10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2019-01-23-22:05:21
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpqw2efpds/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Evaluation [5000/10000]
INFO:tensorflow:Evaluation [6000/10000]
INFO:tensorflow:Evaluation [7000/10000]
INFO:tensorflow:Evaluation [8000/10000]
INFO:tensorflow:Evaluation [9000/10000]
INFO:tensorflow:Evaluation [10000/10000]
INFO:tensorflow:Finished evaluation at 2019-01-23-22:05:29
INFO:tensorflow:Saving dict for global step 10000: average_loss = 0.5139621, global_step = 10000, label/mean = 0.018339898, loss = 16.446787, prediction/mean = -0.014618424
INFO:tensorflow:Saving 'checkpoint_path

In [24]:
metricas_treinamento

{'average_loss': 0.5055223,
 'label/mean': -0.0077094375,
 'loss': 16.176714,
 'prediction/mean': -0.018214094,
 'global_step': 10000}

In [25]:
metricas_teste

{'average_loss': 0.5139621,
 'label/mean': 0.018339898,
 'loss': 16.446787,
 'prediction/mean': -0.014618424,
 'global_step': 10000}

In [26]:
import numpy as np
novas_casas = np.array([[800], [900], [1000]])
novas_casas

array([[ 800],
       [ 900],
       [1000]])

In [27]:
novas_casas = scaler_x.transform(novas_casas)
novas_casas

/home/luizbag/anaconda3/envs/tensorflow/lib/python3.6/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


array([[-1.39358923],
       [-1.28470655],
       [-1.17582386]])

In [28]:
funcao_previsao = tf.estimator.inputs.numpy_input_fn({'x': novas_casas}, shuffle = False)

In [29]:
previsoes = regressor.predict(input_fn = funcao_previsao)

In [30]:
previsoes

<generator object Estimator.predict at 0x7f7d4021c0a0>

In [31]:
list(previsoes)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpqw2efpds/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


[{'predictions': array([-0.97261053], dtype=float32)},
 {'predictions': array([-0.8979665], dtype=float32)},
 {'predictions': array([-0.8233224], dtype=float32)}]

In [32]:
for p in regressor.predict(input_fn = funcao_previsao):
    #print(p['predictions'])
    print(scaler_y.inverse_transform(p['predictions']))

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpqw2efpds/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
[183024.61]
[210427.83]
[237831.08]
