In [87]:
import pandas as pd
base = pd.read_csv('breast-cancer.csv')
base.head()

code_number  clump_thickness  uniformity_cell_size  uniformity_cell_shape  \
0      1000025                5                     1                      1   
1      1002945                5                     4                      4   
2      1015425                3                     1                      1   
3      1016277                6                     8                      8   
4      1017023                4                     1                      1   

   marginal_adhesion  single_epitelial_cell_size  bare_nuclei  \
0                  1                           2            1   
1                  5                           7           10   
2                  1                           2            2   
3                  1                           3            4   
4                  3                           2            1   

   bland_chromation  normal_nucleoli  mitoses   class  
0                 3                1        1  benign  
1                 3                2        1  benign  
2                 3                1        1  benign  
3                 3                7        1  benign  
4                 3                1        1  benign

In [53]:
base['mitoses'].unique()

array([ 1,  5,  4,  2,  3,  7, 10,  8,  6])

In [88]:
def converte_classe(rotulo):
    if rotulo == 'benign':
        return 1
    else:
        return 0

In [55]:
def desgracado(rotulo):
    if rotulo == '?':
        return 0
    else:
        return rotulo

In [89]:
base['class'] = base['class'].apply(converte_classe)

In [57]:
base['bare_nuclei'] = base['bare_nuclei'].apply(desgracado)

In [90]:
base.head()

code_number  clump_thickness  uniformity_cell_size  uniformity_cell_shape  \
0      1000025                5                     1                      1   
1      1002945                5                     4                      4   
2      1015425                3                     1                      1   
3      1016277                6                     8                      8   
4      1017023                4                     1                      1   

   marginal_adhesion  single_epitelial_cell_size  bare_nuclei  \
0                  1                           2            1   
1                  5                           7           10   
2                  1                           2            2   
3                  1                           3            4   
4                  3                           2            1   

   bland_chromation  normal_nucleoli  mitoses  class  
0                 3                1        1      1  
1                 3                2        1      1  
2                 3                1        1      1  
3                 3                7        1      1  
4                 3                1        1      1

In [59]:
base['class'].unique()

array([1, 0])

In [91]:
X = base.drop(['class', 'code_number'], axis = 1)

In [92]:
X.head()
type(X)

pandas.core.frame.DataFrame

In [93]:
y = base['class']

In [94]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: class, dtype: int64

In [95]:
type(y)

pandas.core.series.Series

In [ ]:
%matplotlib inline
base.age.hist()

In [96]:
import tensorflow as tf

In [97]:
X.columns

Index(['clump_thickness', 'uniformity_cell_size', 'uniformity_cell_shape',
       'marginal_adhesion', 'single_epitelial_cell_size', 'bare_nuclei',
       'bland_chromation', 'normal_nucleoli', 'mitoses'],
      dtype='object')

In [98]:
nome_colunas = ['clump_thickness', 'uniformity_cell_size', 'uniformity_cell_shape',
       'marginal_adhesion', 'single_epitelial_cell_size', 'bare_nuclei',
       'bland_chromation', 'normal_nucleoli', 'mitoses']

In [99]:
colunas = [ tf.feature_column.numeric_column(key = c) for c in nome_colunas ]

In [100]:
print(colunas)

[_NumericColumn(key='clump_thickness', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), _NumericColumn(key='uniformity_cell_size', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), _NumericColumn(key='uniformity_cell_shape', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), _NumericColumn(key='marginal_adhesion', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), _NumericColumn(key='single_epitelial_cell_size', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), _NumericColumn(key='bare_nuclei', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), _NumericColumn(key='bland_chromation', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), _NumericColumn(key='normal_nucleoli', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), _NumericColumn(key='mitoses', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)]


In [101]:
from sklearn.model_selection import train_test_split
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X, y, test_size = 0.3)

In [102]:
X_treinamento.shape
type(X_treinamento)

pandas.core.frame.DataFrame

In [103]:
X_teste.shape
type(y_treinamento)

pandas.core.series.Series

In [104]:
funcao_treinamento = tf.estimator.inputs.pandas_input_fn(x = X_treinamento, y = y_treinamento,
                                                        batch_size = 32, num_epochs = None, shuffle = True)

In [105]:
classificador = tf.estimator.LinearClassifier(feature_columns=colunas)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/tmp/tmpydujzqtm', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7fe5fe260400>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [106]:
classificador.train(input_fn=funcao_treinamento, steps = 10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 0 into /tmp/tmpydujzqtm/model.ckpt.
INFO:tensorflow:loss = 22.18071, step = 1
INFO:tensorflow:global_step/sec: 274.672
INFO:tensorflow:loss = 5.8612676, step = 101 (0.370 sec)
INFO:tensorflow:global_step/sec: 416.838
INFO:tensorflow:loss = 7.1168737, step = 201 (0.237 sec)
INFO:tensorflow:global_step/sec: 418.816
INFO:tensorflow:loss = 6.6180563, step = 301 (0.242 sec)
INFO:tensorflow:global_step/sec: 407.618
INFO:tensorflow:loss = 4.2801223, step = 401 (0.243 sec)
INFO:tensorflow:global_step/sec: 414.738
INFO:tensorflow:loss = 1.7743499, step = 501 (0.241 sec)
INFO:tensorflow:global_step/sec: 414.71
INFO:tensorflow:loss = 4.524853, step = 601 (0.241 sec)
INFO:tensorflow:global_step/sec: 430.177
INFO:tensorflow:los

INFO:tensorflow:global_step/sec: 434.266
INFO:tensorflow:loss = 1.5463921, step = 8101 (0.230 sec)
INFO:tensorflow:global_step/sec: 423.611
INFO:tensorflow:loss = 0.702387, step = 8201 (0.236 sec)
INFO:tensorflow:global_step/sec: 418.447
INFO:tensorflow:loss = 2.3027472, step = 8301 (0.239 sec)
INFO:tensorflow:global_step/sec: 428.802
INFO:tensorflow:loss = 2.170863, step = 8401 (0.233 sec)
INFO:tensorflow:global_step/sec: 422.066
INFO:tensorflow:loss = 8.319458, step = 8501 (0.237 sec)
INFO:tensorflow:global_step/sec: 433.685
INFO:tensorflow:loss = 1.8467128, step = 8601 (0.231 sec)
INFO:tensorflow:global_step/sec: 420.879
INFO:tensorflow:loss = 0.6903821, step = 8701 (0.237 sec)
INFO:tensorflow:global_step/sec: 423.073
INFO:tensorflow:loss = 4.849005, step = 8801 (0.236 sec)
INFO:tensorflow:global_step/sec: 393.851
INFO:tensorflow:loss = 2.8751664, step = 8901 (0.259 sec)
INFO:tensorflow:global_step/sec: 405.125
INFO:tensorflow:loss = 0.98092055, step = 9001 (0.242 sec)
INFO:tensorfl

In [107]:
funcao_previsao = tf.estimator.inputs.pandas_input_fn(x = X_teste, batch_size = 32, shuffle = False)

In [108]:
previsoes = classificador.predict(input_fn=funcao_previsao)

In [109]:
list(previsoes)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpydujzqtm/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


[{'logits': array([5.593096], dtype=float32),
  'logistic': array([0.9962903], dtype=float32),
  'probabilities': array([0.00370967, 0.9962903 ], dtype=float32),
  'class_ids': array([1]),
  'classes': array([b'1'], dtype=object)},
 {'logits': array([-9.228295], dtype=float32),
  'logistic': array([9.821088e-05], dtype=float32),
  'probabilities': array([9.9990177e-01, 9.8210876e-05], dtype=float32),
  'class_ids': array([0]),
  'classes': array([b'0'], dtype=object)},
 {'logits': array([4.5171943], dtype=float32),
  'logistic': array([0.9891984], dtype=float32),
  'probabilities': array([0.01080167, 0.9891984 ], dtype=float32),
  'class_ids': array([1]),
  'classes': array([b'1'], dtype=object)},
 {'logits': array([4.4988713], dtype=float32),
  'logistic': array([0.9890008], dtype=float32),
  'probabilities': array([0.01099921, 0.9890008 ], dtype=float32),
  'class_ids': array([1]),
  'classes': array([b'1'], dtype=object)},
 {'logits': array([2.7412028], dtype=float32),
  'logistic':

In [110]:
previsoes_final = []
for p in classificador.predict(input_fn=funcao_previsao):
    previsoes_final.append(p['class_ids'])

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpydujzqtm/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


In [111]:
previsoes_final

[array([1]),
 array([0]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([0]),
 array([1]),
 array([0]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([0]),
 array([0]),
 array([0]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([0]),
 array([0]),
 array([1]),
 array([1]),
 array([0]),
 array([1]),
 array([1]),
 array([0]),
 array([0]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([0]),
 array([1]),
 array([1]),
 array([0]),
 array([0]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([0]),
 array([1]),
 array([1]),
 array([1]),
 array([0]),
 array([0]),
 array([1]),
 array([0]),
 array([1]),
 array([0]),
 array([0]),
 array([1]),
 array([1]),
 array([1]),
 array([0]),
 array([1]),
 array([0]),
 array([1]),
 array([1]),
 array([1]),
 array([0]),
 array([1]),
 array([1]),
 array([0]),
 array([1]),
 array([1]),

In [112]:
from sklearn.metrics import accuracy_score
taxa_acerto = accuracy_score(y_teste, previsoes_final)
taxa_acerto

0.9476190476190476